### ISSUE TITLE
No module named 'numpy'

### ISSUE THREAD

**Issue by xfopl** [Stanou01260/chessbot_python#4]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    import chessboard_detection
  File "/Users/aleksandrveselov/Desktop/chessbot_python-master/code/chessboard_detection.py", line 1, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by AbdelH2O** [comment]
Try running "pip install numpy".
And make sure you're using the correct pip by typing "which pip" (it has to be the same directory as your python interpreter).
